# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d971acc4c8f941694d34514fbb8a9fa1fab40a651be4c7ddaac14373fb888da447bf5183b56a09aebc31b72b349fedc15a56f26f1fca1a868cc178b07c5eb5c

test:
  secret_key_base: f20b2326515377c72f5df1adf0963b449b450e89b77c121be879c7bf1f5c86e384c5fa960c3a8b06bbd223da9dfd8a6b4e7b6a1e7bebca3796d3a6ebb82bdc63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
